[package]
name = "rusted_vulkans"
version = "0.1.0"
authors = ["Jerome Stepp <exohuman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
