[package]
name = "basic_window"
version = "0.1.0"
authors = ["jerome"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windower = { path = "../windower" }
